KVSlab/morphMan

src/common.py

The no_smooth_point should be stored in *_info.txt, and should be read from *_info.txt if present.

Look for previous no_smooth_point in *_info.txt

---

test/fixtures.py

Tested with Anaconda 5.3 on Windows 10 Pro.

Test suite now compatible on Windows.

---

CONTRIBUTING.md

[Issue #13] Created guidelines for contributing (draft), including a code of conduct.

---

.travis.yml
appveyor.yml
conda-build/bld.bat
conda-build/build.sh
conda-build/conda_build_config.yaml
conda-build/meta.yaml
continuous-integration/appveyor/install.ps1
docs/source/Miscellaneous.rst
docs/source/installation.rst
docs/source/manipulate_area.rst
docs/source/manipulate_bend.rst
docs/source/manipulate_bifurcation.rst
docs/source/manipulate_curvature.rst
morphman/manipulate_area.py

* Conda installation works on all platforms using `conda install -c morphman -c vmtk morphman`
* Documentation updated with a simplified installation guideline, including installation / building the developer version

[Issue #14] Python module setup + conda distribution

---

.travis.yml
appveyor.yml

Appveyor script refactored to act in a similar manner as on travis-ci. Fixes issues with conda-build on current version of morphman master branch.

Appveyor buildfix

---

paper/paper.md

This should improve the look of multiple references in the paper.

Reference formatting.

---

morphman/common/common.py
morphman/common/surface_operations.py
test/fixtures.py

Replace homemade solution with json for storing parameters.
Resolving issue #5.

Change to json

---

morphman/common/centerline_operations.py
morphman/common/surface_operations.py
morphman/common/vmtk_wrapper.py
morphman/common/vtk_wrapper.py
morphman/manipulate_branch.py

- Added additional input parameters to VTK and VMTK wrappers, making the methods more general and flexible. 
- Corresponding documentation added for each parameter, partly borrowed from the official VTK and VMTK documentation. 
- Minor refactoring, including separating commonly used methods into their respective common-file.

[#2] VTK / VMTM Method generalization

---

docs/source/getting_started.rst
docs/source/manipulate_surface.rst
morphman/common/centerline_operations.py
morphman/manipulate_bifurcation.py
test/test_manipulate_bifurcation.py

Fix small bugs in bifurcation which caused unexpected behavior when using default values.

Bugfix bifurcation

---

morphman/common/vmtk_wrapper.py
morphman/manipulate_branch.py

- Algorithm allows user to select any branch of the geometry, including downstream branches.
- If branch is selected manually, the shortest possible branch is chosen.
- Number of possible branches to manipulate has increased to `2 * Number of bifurcations` 
- Fixes issue #33

Select all / downstream branches

---

CONTRIBUTING.md
README.md
morphman/common/centerline_operations.py
morphman/common/common.py
morphman/common/surface_operations.py
morphman/manipulate_area.py
morphman/manipulate_bend.py
morphman/manipulate_bifurcation.py
morphman/manipulate_branch.py
morphman/manipulate_curvature.py
morphman/manipulate_surface.py
morphman/misc/automated_landmarking.py
morphman/misc/estimate_alpha_and_beta.py
test/fixtures.py
test/test_landmarking.py

- Refactoring of .py and .md files
- Renamed unused variables to `_` from methods returning multiple variables
- Usage of `enumerate` in for loops, when convenient 
- Removed blank spaces & compact method calls

Refactoring based on Codacy anaylsis

---

morphman/misc/automated_landmarking.py

- Refactored saving of landmarking points using Json format.
- Removed duplicate landmarking points for Piccinelli.
- Updated smoothing factors to Piccinelli reference.
- Refactored way of finding torsion and curvature max for Piccinelli method

Updates to Landmarking script

---

morphman/common/surface_operations.py
morphman/common/vtk_wrapper.py
morphman/misc/automated_landmarking.py
test/test_landmarking.py

- Replaced static cell locator with standard cell locator
- Updated params of Piccinelli method to replicate result in paper
- Removed .vtp-restriction on Landmarking model

VTK & Landmark updates

---

.travis.yml
README.md
morphman/common/common.py
morphman/common/surface_operations.py
morphman/common/vmtk_wrapper.py
test/fixtures.py
test/test_centerline_operations.py
test/test_common.py
test/test_surface_operations.py
test/test_vmtk_wrapper.py
test/test_voronoi_operations.py
test/test_vtk_wrapper.py

- Added test coverage for all utility modules
- Removed duplicate `get_centers` method (already exists in `get_inlet_and_outlet_centers`)
- Fixed method for `vmtkCenterlineSmoothing`
~~TODO: Add coverage logging and badge for codecov.io~~

Add test coverage 

---

morphman/common/vmtk_wrapper.py

- Added tortuosity to `vmtk_wrapper` (compute_geometric_features)

Added tortuosity 

---

docs/source/installation.rst

- Temporary fix until VMTK is updated
- Issue experienced so far only on Linux

Add temporary fix for missing dependency/library

---

.circleci/config.yml
README.md
appveyor.yml
docs/source/installation.rst

- Updated installation steps for CI, in documentation & readme to download/install morphman through conda-forge

Move morphMan to conda-forge

---

morphman/common/centerline_operations.py
morphman/manipulate_surface.py

- Detect early diverging centerlines, located before clipping points

Hotfix for detecting diverging centerlines

---

morphman/common/centerline_operations.py
morphman/common/surface_operations.py

- Refactor centerline tolerance
- Perform light smoothing before extracting boundaries
Fixes issues addressed in #72

Refactor centerline tolerance 

---

.circleci/config.yml
morphman/common/surface_operations.py

- Added slight downscaling of normal vectors to avoid round off errors during preparation of output surface
Fixes issue #77

Hotfix for prepare_output_surface
